"""remover admin usuario

Revision ID: 7ecabdec423f
Revises: 6d80a5480493
Create Date: 2025-06-12 18:14:13.596132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ecabdec423f"
down_revision: Union[str, None] = "6d80a5480493"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("usuarios", sa.Column("admin", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
